packages:
  - packages/*
  - test-helpers
  - fixtures/*
  - fixtures/thirdparty/**
  - site
  - examples/*
  - tests
  - benchmarks
  - scripts
onlyBuiltDependencies:
  - esbuild
preferWorkspacePackages: true
