blank_issues_enabled: false
contact_links:
  - name: Feature requests, Questions & Discussions
    url: https://github.com/seek-oss/vanilla-extract/discussions
    about: Use GitHub discussions for message-board style questions and discussions
  - name: Discord Chat
    url: https://discord.gg/6nCfPwwz6w
    about: Ask questions and discuss with other vanilla-extract users in real time.